[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "./netlify/plugins/asset-headers"

[functions]
  directory = "netlify/functions"

# API route redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Image proxy redirects
[[redirects]]
  from = "/proxy-image/*"
  to = "/.netlify/functions/image-proxy/:splat"
  status = 200

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Fix MIME type issues for assets
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"