// Sample planned apps for demo purposes
export const samplePlannedApps = [
  {
    name: "Jusbrasil",
    description: "Aplicativo para consulta de processos jurídicos e acompanhamento de ações.",
    thumbnailUrl: "https://via.placeholder.com/300x200?text=Jusbrasil",
    logo: "https://via.placeholder.com/100x100?text=JB",
    type: "Federal",
    category: "Cidadania",
    platform: "Cross-platform",
    language: "Portuguese",
    screenCount: 0,
    url: "https://example.com/jusbrasil",
    status: "Planejado",
    airtableId: "rec14",
  },
  {
    name: "Resultados",
    description: "Aplicativo para consulta de resultados de exames e laudos médicos.",
    thumbnailUrl: "https://via.placeholder.com/300x200?text=Resultados",
    logo: "https://via.placeholder.com/100x100?text=RE",
    type: "Federal",
    category: "Saúde",
    platform: "iOS",
    language: "Portuguese",
    screenCount: 0,
    url: "https://example.com/resultados",
    status: "Planejado",
    airtableId: "rec15",
  },
  {
    name: "Conecta Cidadão",
    description: "Aplicativo de conexão direta entre cidadãos e serviços públicos municipais.",
    thumbnailUrl: "https://via.placeholder.com/300x200?text=Conecta+Cidadão",
    logo: "https://via.placeholder.com/100x100?text=CC",
    type: "Municipal",
    category: "Portal",
    platform: "Cross-platform",
    language: "Portuguese",
    screenCount: 0,
    url: "https://example.com/conectacidadao",
    status: "Planejado",
    airtableId: "rec16",
  },
  {
    name: "MEI Fácil",
    description: "Aplicativo para microempreendedores individuais gerenciarem suas obrigações fiscais.",
    thumbnailUrl: "https://via.placeholder.com/300x200?text=MEI+Fácil",
    logo: "https://via.placeholder.com/100x100?text=MEI",
    type: "Federal",
    category: "Finanças",
    platform: "Cross-platform",
    language: "Portuguese",
    screenCount: 0,
    url: "https://example.com/meifacil",
    status: "Planejado",
    airtableId: "rec17",
  }
];